name: Docker setup for WebGoat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: WebGoat/WebGoat@v8.2.1
      
      - uses: actions/checkout@v2
      
      - name: docker build
        run: |
          docker run -it -p 127.0.0.1:80:8888 -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf:v8.2.2

 
      - name: Run a multi-line script
        run: |
          echo Hello,
          echo This is the end line.
