name: Docker setup for WebGoat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      
      - name: docker build
        run: |
          docker run -d -p 127.0.0.1:8080:8022 webgoat/webgoat-8.0
          sleep 30

 
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
         target: "http://127.0.0.1:8080/WebGoat"

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: /

      - uses: actions/download-artifact@v2
        with: 
          name: my-artifact
