name: Docker setup for WebGoat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      
      - name: docker build
        run: |
          docker run -p 127.0.0.1:80:8888 -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf:v8.2.2

 
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
         target: "http://localhost:8080/WebGoat"
